### ISSUE TITLE
Tapping the (i) button next to player name does nothing

### ISSUE THREAD

**Issue by chris-shortall** [Kurgol/samba-action-calculator#5] opened 2017-10-13 09:31 UTC
I would expect this to open the player details to view/edit their skills like Dodge.

**Comment by kurgol** [comment] 2017-10-13 10:05
If you click anywhere on the row other than the "i" it does, not sure what the intended behaviour was in the original app, but agree behaviour is not ideal.

**Comment by Kurgol** [comment] 2017-10-16 09:35
should be resolved by #11

**Comment by kurgol** [comment] 2017-10-16 09:36
should be resolved by #11

**Closed as completed by kurgol** 2017-10-16 09:36 UTC
Labels: help wanted
